name = "etyping-variety-rankings"
main = "src/workers/index.ts"
compatibility_flags = [ "nodejs_compat_v2" ]
compatibility_date = "2025-06-24"

browser = { binding = "MYBROWSER" }

[[d1_databases]]
binding = "DB"
database_name = "e-typing-variety-rankings"
database_id = "0852d5b4-268d-4c2f-9c78-57a7c0e4feaa"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"

[env.production]
name = "etyping-ranking-api"

[env.staging]
name = "etyping-ranking-api-staging"
